dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
- touch ~/.ssh/appuser.pub && touch ~/.ssh/appuser
- sudo pip install --upgrade pip && sudo pip install ansible && sudo pip install ansible-lint
- cd /tmp && wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  && unzip terraform_0.11.7_linux_amd64.zip && sudo mv terraform /usr/local/bin &&
  wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
  && unzip tflint_linux_amd64.zip && sudo mv tflint /usr/local/bin/ && cd -
- cd terraform/prod && cp -v terraform.tfvars.example terraform.tfvars && terraform
  init -backend=false && terraform validate && tflint *.tf && cd -
- cd terraform/stage && terraform init -backend=false && cp -v terraform.tfvars.example
  terraform.tfvars && terraform validate && tflint *.tf && cd -
- find packer/*.json -type f -print0 | xargs -0 -n1 packer validate -var-file packer/variables.json.example
- cd ansible/playbooks && ansible-lint *.yml && cd -
notifications:
  slack:
    secure: mzywBgcZ8F3Cb/sJ+IOCKbvFX+ViY5pG72fkFCNCKi5Fmhhlvpr4J1RpIdzI86kAneYMLzCmDrBBm+xcUfamGif608cEYoFzALBwtCBidgmijCX6oBVtlQkFBZiegocxMOGG3+NRpKqdsLs+tcY+frGfhgVL7ORaXX/yr+GVmEcP9hzUzjS8G+bgQjV0ndybEm+WCYcbCUYcKnPCYkuxA4bVjG9vSNHIf+HlS3RXCa7BQn5OIScRNuvdlXOGyCkXUURwj5W0BqkJF4jwB4+ZkVSmkV4rntnxfTY3nsiCZtqEM+Gra0S/PpLEC8Dt2dIZpH8wEpxcsXh+KjJRJjYGEdfllu80DZooVtIjff4hFb68+iTCvcyVntQ9r2GnnB+IR973MwqiBHoExlek1fGbhxMsd9Q+hsfBWENqbJPX80WHmzwGLtIUFcTiUk2tVmMzB01/vZlDDikLvht4XvGT144MCO+x4SOFwRCz7WH8rfPPE07VKHi2WoGb4De3gSJCClLRqnrw3/XI6YfON1R4fD0q7Ka+mI5c0NnpF25tF0EM7u1cdUHadUSCzHyBIDKCH1M4Ke9h+9u6TALMA9vTwcse4k0kUkuNdUAeXL78oBMSFUMVZS1TNXL4Iyae7+xyr9hf3noV5Apu2mJ+1zjJefjhUeJDPyCPZ18wVstc+Ek=
