- name: Configule application
  become: true  
  hosts: reddit-app
  debugger: on_failed
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

  handlers:
  - name: enable puma
    systemd: name=puma enabled=yes

  - name: reload puma
    systemd: name=puma state=restarted

